### ISSUE TITLE
Problem rendering equations

### ISSUE THREAD

**Issue by vPibernus** [openturns/otfmi#119]
Some equations in the documentation pages are poorly rendered, making them difficult to understand.

- Page: The cantilever beam model ([Link to page](https://openturns.github.io/otfmi/master/fmus/deviation.html))
    - Problem: The cantilever beam deflection equation is broken.

- Page: The epidemiological model ([Link to page](https://openturns.github.io/otfmi/master/fmus/epid.html))
    - Problem: The epidemiological model equations are broken.

- Page: Sensitivity analysis with Persalys ([Link to page](https://openturns.github.io/otfmi/master/demo_persalys/use_persalys.html))
    - Problem: The mathematical symbols in the solar collector equations are incorrectly rendered.
    
- Page: Estimate the probability of a threshold excedance ([Link to page](https://openturns.github.io/otfmi/master/auto_application/plot_cantilever_beam.html))
    - Problem: The equations for the probability of a threshold exceedance for the embedded beam model are broken.

**Suggested solution:** Check and correct the LaTeX or MathJax rendering for each affected equation.

**Comment by mbaudin47** [comment]
@jschueller, @vPibernus : Thank you very much for fixing these equations!
