### ISSUE TITLE
Improved formatting of Python code in documentation

### ISSUE THREAD

**Issue by vPibernus** [openturns/otfmi#120]
Python code formatting is inconsistent, with incorrect syntax highlighting choices.

- Page: Metamodel a FMU time-dependent output ([Link to page](https://openturns.github.io/otfmi/master/auto_application/plot_metamodel.html))
    - Problem: Syntax highlighting turns some parts of the code completely green, which is not normal.

**Suggested solution:** Use a standardised syntax highlighting tool (such as Pygments) or adjust the highlighting parameters.

**Comment by jschueller** [comment]
pygment is used here, but these are hyperlinks (intersphinx)
