### ISSUE TITLE
Is this library helpful to improve initialization robustness of Modelica models?

### ISSUE THREAD

**Issue by Satinelamp** [openturns/otfmi#52]

**Comment by SG-phimeca** [comment]
Hello,

That depends on what you mean by “initialization”.

If you mean “getting the solver to start by solving the initial conditions problem”, then Otfmi will probably not be very useful.

However, if you mean “finding a particular state from the solution space in good adequation with some data”, then yes, Otfmi can definitely help by giving you access to optimization or bayesian inference methods from OpenTURNS. 
You may want to [have a look at this paper for inspiration](https://sylvaingirard.net/pdf/gerrer20-health_monitoring_digital_twins.pdf) (the objective is different, but it may give you some ideas). Feel free to contact me directly by email (see my profile) for additional details.

Kind regards
