### ISSUE TITLE
Get listed on the FMI tools page https://fmi-standard.org/tools/ and provide compatibility information

### ISSUE THREAD

**Issue by chrbertsch** [openturns/otfmi#97]
see [https://github.com/modelica/fmi-standard.org/blob/main/CONTRIBUTING.md#updating-the-tools-list](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmodelica%2Ffmi-standard.org%2Fblob%2Fmain%2FCONTRIBUTING.md%23updating-the-tools-list&data=05%7C01%7CChristian.Bertsch%40de.bosch.com%7C01cb7050c3044b3d2c2e08dbd1ac4020%7C0ae51e1907c84e4bbb6d648ee58410f4%7C0%7C0%7C638334309952318885%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hYwrAF54HTQl9rSZlySOaDo23KhHiyntR49uLRztRow%3D&reserved=0)

For the examplesURL you are encouraged to provide a link to a webpage or repo where you document how you tested your tool w.r.t to FMI support. So you could list that you tested the import with the reference FMUs. See e.g. [https://github.com/altairengineering/fmus](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faltairengineering%2Ffmus&data=05%7C01%7CChristian.Bertsch%40de.bosch.com%7C01cb7050c3044b3d2c2e08dbd1ac4020%7C0ae51e1907c84e4bbb6d648ee58410f4%7C0%7C0%7C638334309952318885%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7cblzvmoxG496WskCZUVcxnJzQU8aDUxkUDtydXdl2A%3D&reserved=0) for an example

Thanks in advance!

**Comment by jschueller** [comment]
I think it doesnt apply to otfmi since we rely on pyfmi, and pyfmi is already listed there

**Comment by chrbertsch** [comment]
> I think it doesnt apply to otfmi since we rely on pyfmi, and pyfmi is already listed there

This is what you could provide as part of the the "Compatibility Information." It will help users.
Additionally, pyfmi has not yet provided "compatibility information" (see https://github.com/modelon-community/PyFMI/issues/202)
So if you describe with which FMUs from which tool vendors you have tested your implementation, this would be more than we have today.

Getting listed on the FMI tools page https://fmi-standard.org/tools/  is anyway recommended, so that potential users are aware of your FMI support. It is minimal effort: just create a pull request according to https://github.com/modelica/fmi-standard.org/blob/master/CONTRIBUTING.md#updating-the-tools-list

Thanks in advance
